= How to use this tool

== Direct usage

[source]
mvn clean compile exec:java -Dexec.args="args go here"

== Dockerfile

A Dockerfile is provided for ease of running without necessary environment (JDK, Maven, etc.)

Simply do:

[source]
----
docker build -t jenkins/usage-in-plugins .

# Run it
docker run -ti \
           -v maven-repo:/root/.m2/repository \
           -v downloaded-plugins:/project/work \
           -v $PWD/output:/project/output \
              jenkins/usage-in-plugins
...

# Run it on a subset of classes (with all sample output)
$ cat add.txt
javax/xml/bind/DatatypeConverterImpl
javax/xml/bind/DatatypeConverter
$ docker run -ti \
           -v maven-repo:/root/.m2/repository \
           -v downloaded-plugins:/project/work \
           -v $PWD/output:/project/output \
           -v $PWD/add.txt:/project/additional-classes.txt:ro \
              jenkins/usage-in-plugins -C additional-classes.txt -i
Downloaded update-center.json
All files are up to date (1590 plugins)
Analyzing deprecated api in Jenkins
additional-classes.txt found, adding 2 classes
        adding javax/xml/bind/DatatypeConverterImpl
        adding javax/xml/bind/DatatypeConverter
Analyzing deprecated usage in plugins
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.........Writing output/usage-by-plugin.json
Writing output/usage-by-plugin.html
Writing output/deprecated-and-unused.json
Writing output/deprecated-and-unused.html
Writing output/usage-by-api.json
Writing output/usage-by-api.html
----

=== Finding Usage of Methods and Fields

The command line flag `-M filename.txt` or `--additionalMethods filename.txt` allows you to search for specific methods.
Use the additional flag `-i` or `--onlyIncludeSpecified` to only show usage of specified classes, methods, and fields.
For example, to find usage of `hudson.util.Secret.toString`, include the following line in the specified file:

[source]
----
hudson.util.Secret#toString
----

Specify class names in their fully qualified form (i.e., inner classes should be referenced via `Outer$Inner` rather than by their canonical names).
Specify method names after the hash.
You cannot specify distinct method signatures. All variants are included in reports.

The command line flag `-F filename.txt` or `--additionalFields filename.txt` allows you to find specific field usages.
The syntax here is the same as for specifying method names.
Use the additional flag `-i` or `--onlyIncludeSpecified` to only show usage of specified classes, methods, and fields.

=== Finding Usage by Package

By using just a package name instead of the fully qualified class name in any of the options above, this searches for classes that start with the same specified package.
For example, the following snippet would search for usage of methods or fields named `toString` in any classes inside the `hudson.util` package or its descendants.
Note the trailing `.` before the `#` separator which makes the search more specific to `hudson.util` rather than also including the hypothetical package `hudson.utils` or `hudson.utility`.

[source]
----
hudson.util.#toString
----

=== Configuring Parallelism

The default parallelism settings will allow up to 4x the number of available CPUs downloads at a time.
This can be overridden by the `-D N` or `--downloadConcurrent=N` option for some number `N`.
