= How to use this tool

== Direct usage

[source]
mvn clean compile exec:java

== Dockerfile

A Dockerfile is provided for ease of running without necessary environment (JDK, Maven, etc.)

Simply do:

[source]
----
docker build -t jenkins/usage-in-plugins .

# Run it
docker run -ti \
           -v maven-repo:/root/.m2/repository \
           -v downloaded-plugins:/project/work \
           -v $PWD/output:/project/output \
              jenkins/usage-in-plugins
...

# Run it on a subset of classes (with all sample output)
$ cat add.txt
javax/xml/bind/DatatypeConverterImpl
javax/xml/bind/DatatypeConverter
$ docker run -ti \
           -v maven-repo:/root/.m2/repository \
           -v downloaded-plugins:/project/work \
           -v $PWD/output:/project/output \
           -v $PWD/add.txt:/project/additional-classes.txt:ro \
              jenkins/usage-in-plugins --additionalClasses additional-classes.txt --onlyAdditionalClasses
Downloaded update-center.json
All files are up to date (1590 plugins)
Analyzing deprecated api in Jenkins
additional-classes.txt found, adding 2 classes
        adding javax/xml/bind/DatatypeConverterImpl
        adding javax/xml/bind/DatatypeConverter
Analyzing deprecated usage in plugins
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.......... .......... .......... .......... ..........
.........Writing output/usage-by-plugin.json
Writing output/usage-by-plugin.html
Writing output/deprecated-and-unused.json
Writing output/deprecated-and-unused.html
Writing output/usage-by-api.json
Writing output/usage-by-api.html
----

=== Finding Usage of Methods and Fields

The command line flag `-M filename.txt` or `--additionalMethods filename.txt` allows specific methods to be searched for.
The additional flag `--onlyAdditionalMethods` will filter the output report to only show usage of the methods specified.
For example, to find usage of `hudson.util.Secret.toString`, the following line should be included in the specified file:

[source]
----
hudson/util/Secret#toString
----

Class names should be specified in their fully qualified form (i.e., inner classes should be referenced via `Outer$Inner` rather than by their canonical names).
Method names should be specified after the hash.
Note that you cannot specify which method overload signature, but they are included in reports.

The command line flag `-F filename.txt` or `--additionalFields filename.txt` allows specific field usages to be found.
The syntax here is the same as for specifying method names.
The additional flag `--onlyAdditionalFields` will filter the output report to only show usages of the fields specified.
